# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-18 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='User',
            new_name='user',
        ),
    ]
